@startuml diagrama
class Main {
  main()
}
class Bot {
  jda
  moduleManager
  start()
}
class EventListener {
  isCommandEnabled
  onMessageReceived()
  onMessageReactionAdd()
  setCommandEnabled()
  isCommandEnabled()
}
EventListener --|> ListenerAdapter
class ModuleManager {
  modules
  registerModule()
  enableModule()
  disableModule()
  isModuleEnabled()
  getModules()
}
class CommandManager {
  commands
  getSlash()
  onSlashCommandInteraction()
}
CommandManager --|> EventListener
class ModCommands {
}
ModCommands --|> CommandManager
class ManageCommands {
}
ManageCommands --|> CommandManager
class UserCommands {
}
UserCommands --|> CommandManager
class Ban {
  name
  execute()
  getSlash()
  getName()
}
Ban ..|> ICommand
class Kick {
  name
  execute()
  getSlash()
  getName()
}
Kick ..|> ICommand
class Mute {
  name
  execute()
  getSlash()
  getName()
}
Mute ..|> ICommand
class DatabaseManager {
  url
  user
  password
  connection
  connect()
  addPenalty()
  getPenalties()
  close()
}
class Utils {
  isValidUserId()
  formatPenaltyMessage()
  formatDuration()
}
class GuiManager {
  initializeGui()
  updateGui()
}
@enduml
