name: Generate Class Diagram

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y plantuml graphviz

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Generate UML diagram
      run: ./gradlew generateUML

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add class-diagram.png
        git commit -m 'Add generated UML diagram'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload UML diagram
      uses: actions/upload-artifact@v3
      with:
        name: class-diagram
        path: class-diagram.png