name: Generate Class Diagram

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y plantuml graphviz

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Generate Javadoc
      run: ./gradlew javadoc

    - name: Generate UML diagram
      run: |
        mkdir -p build/plantuml
        plantuml -tpng -o build/plantuml build/docs/javadoc

    - name: Upload UML diagram
      uses: actions/upload-artifact@v3
      with:
        name: class-diagram
        path: build/plantuml